
####################################
######     Global start     ######
####################################
name                : 'Becore'
title               : 'Softdash - Creative SaaS And Software HTML5 Jekyll Template'
email               : demo@example.com
address             : '2216 Park Avenue, California 95630 '
phone               : 0185612012035
tagline             : 'description for your new site here' 
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl             : "" # the subpath of your site, e.g. /blog
url                 : "https://laughing-hypatia-1962bd.netlify.com/" #  7277783  the base hostname & protocol for your site, e.g. http://example.com
twitter_username    : jekyllrb
github_username     :  jekyll
favicon: 'img/favicon.png'

paginate: 12
paginate_path: "/blog/page:num/"

sass:
    sass_dir: _sass
    style: compressed

# Build settings
markdown            : kramdown

# all plugin
plugins:
  - jekyll-feed

# google_analytics
google_analytics: ''

# disqus comment
disqus:
  shortname: ''


####################################
######     Hero start     ######
####################################
# product_background_image          sass
# product_fixed_image               saas_video             
# product                           sass_background_image
# product_slider                    sass_fixed_image
# product_video                     sass_slider       

hero: 'product_fixed_image'

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache

####################################
######      Global end      ######
####################################


getform_id: # active contact https://getform.io/f/1234



mailchimp:
  user-id: 
  list-id: 


####################################
######        Copyright       ######
####################################
copyright_text: Copyright © 2019 All rights reserved to
company_url: '#'


# SEO Related
google_site_verification :
bing_site_verification   :
yandex_site_verification :
naver_site_verification  :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : # Open Graph/Twitter default site image
# For specifying social profiles
# - https://developers.google.com/structured-data/customize/social-profiles
social:
  type                   : # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Analytics
analytics:
  provider               : false # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :
    anonymize_ip         : # true, false (default)

timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

#google map api key

map: 'AIzaSyA7nx22ZmINYk9TGiXDEXGVxghC43Ox6qA'