name: Deploy Main Site to GitHub Pages
on:
  push:
    branches: ["main"]
    paths:
      - "landing/**"
      - ".github/workflows/deploy-main.yml"
  pull_request:
    branches: [main]
    paths:
      - "landing/**"
      - ".github/workflows/deploy-main.yml"
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd landing
          npm ci
      - run: |
          cd landing
          npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: landing/dist
          cname: www.plexicus.ai
